spring:
  application:
    name: Climalert
    testing: true
  mail:
    active: false
    host: HOST-EXAMPLE
    port: PORT-EXAMPLE
    username: USERNAME-EXAMPLE
    password: PASSWORD-EXAMPLE
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
weather:
  api:
    key: API-KEY-EXAMPLE
email:
  alertas:
    remitente: "noreply@climalert.com"
    destinatarios: "admin@clima.com,emergencias@clima.com,metereologia@clima.com"

cron.alertas: 60000
cron.notificacion: 60000
cron.clima: 300000